#pragma once

typedef enum
{
    // Only included noteworthy ones for now
    ATLAS_FACE_DEBUG_0 = 0,
    ATLAS_FACE_DEBUG_1 = 1,
    ATLAS_FACE_DEBUG_2 = 2,
    ATLAS_FACE_DEBUG_3 = 3,
    ATLAS_FACE_DEBUG_4 = 4,
    ATLAS_FACE_DEBUG_5 = 5,
    // Error texture bc shouldnt render air
    ATLAS_FACE_AIR = 0,
    ATLAS_FACE_UNDEFINED = 0,
    ATLAS_FACE_STONE = 1,
    ATLAS_FACE_DIORITE = 2,
    ATLAS_FACE_ANDESITE = 3,
    ATLAS_FACE_GRANITE = 4,
    ATLAS_FACE_CHERT = 5,
    ATLAS_FACE_SHALE = 6,
    ATLAS_FACE_CHALK = 7,
    ATLAS_FACE_LIMESTONE = 8,
    ATLAS_FACE_JASPER = 9,
    ATLAS_FACE_SLATE = 10,
    ATLAS_FACE_SANDSTONE_YELLOW = 11,
    ATLAS_FACE_SANDSTONE_RED = 12,
    ATLAS_FACE_MARBLE_BLACK = 13,
    ATLAS_FACE_MARBLE_WHITE = 14,
} AtlasFace_t;