#pragma once

typedef enum
{
    INPUT_ACTION_UNMAPPED = 0,
    INPUT_ACTION_FULLSCREEN_TOGGLE = 1,
    INPUT_ACTION_MOVE_FORWARD = 2,
    INPUT_ACTION_MOVE_BACKWARD = 3,
    INPUT_ACTION_MOVE_LEFT = 4,
    INPUT_ACTION_MOVE_RIGHT = 5,
    INPUT_ACTION_JUMP = 6,
    INPUT_ACTION_CROUCH = 7,
    INPUT_ACTION_MENU_TOGGLE = 8,
    INPUT_ACTION_WIREFRAME_TOGGLE = 9,
    INPUT_ACTION_SPRINT_TOGGLE = 10,
    INPUT_ACTION_FOV_ZOOM = 11,
    INPUT_ACTION_COUNT,
} InputActionMapping_t;

#define INPUT_ACTION_MAPPING_LONGEST_NAME 32

static const char *INPUT_ACTION_MAPPING_NAMES[] = {
    "INPUT_ACTION_UNMAPPED",
    "INPUT_ACTION_FULLSCREEN_TOGGLE",
    "INPUT_ACTION_MOVE_FORWARD",
    "INPUT_ACTION_MOVE_BACKWARD",
    "INPUT_ACTION_MOVE_LEFT",
    "INPUT_ACTION_MOVE_RIGHT",
    "INPUT_ACTION_JUMP",
    "INPUT_ACTION_CROUCH",
    "INPUT_ACTION_MENU_TOGGLE",
    "INPUT_ACTION_WIREFRAME_TOGGLE",
    "INPUT_ACTION_SPRINT_TOGGLE",
    "INPUT_ACTION_FOV_ZOOM",
};