#pragma once

#include <stdio.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include <signal.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include <stdalign.h>
#include <stddef.h>
#include <string.h>
#include <limits.h>
#include <vulkan/vulkan.h>
#include <GLFW/glfw3.h>
#include "stb_image.h"
#include "cgltf.h"
#include "Logs.h"
#include "Definitions.h"